[[main]]
  identifier = "communes"
  name = "Votre commune"
  url = "departements"
  weight = 1

[[main]]
  identifier = "contribuer"
  name = "Contribuer"
  url = "contribuer"
  weight = 2

# [[main]]
#   identifier = "projets"
#   name = "Projets"
#   url = "projets"
#   weight = 2
