[[main]]
  identifier = "infos"
  name = "Infos"
  url = "infos"
  weight = 1

[[main]]
  identifier = "pads"
  name = "Pads"
  url = "pads"
  weight = 2

# [[main]]
#   identifier = "projets"
#   name = "Projets"
#   url = "projets"
#   weight = 2
