[[main]]
  identifier = "infos"
  name = "Infos"
  url = "infos"
  weight = 1

[[main]]
  identifier = "communes"
  name = "Votre commune"
  url = "departements"
  weight = 2

# [[main]]
#   identifier = "projets"
#   name = "Projets"
#   url = "projets"
#   weight = 2
