logo = false # Logo that appears in the site navigation bar.
logoText = "StopCoronavirus.Tech" # Logo text that appears in the site navigation bar.
logoType = "short" # long, short
description = "Entraide, Annonces, Initiatives pour la gestion du COVID-19" # for SEO

themeOptions = ["light", "dark"] # select options for site color theme

useFaviconGenerator = false # https://www.favicon-generator.org/

enableSearch = false
enableLangChange = false
enableDarkMode = false
enableBreadcrumb = false
enableToc = false
enableMenu = false
enableNavbar = true
enableFooter = true
showPoweredBy = true

paginateWindow = 1 # setting it to 1 gives 7 buttons, 2 gives 9, etc. If set 1: [1 ... 4 5 6 ... 356] [1 2 3 4 5 ... 356] etc
taxoPaginate = 13 # items per page
taxoGroupByDate = "2006" # "2006-01": group by month, "2006": group by year

github = "https://gitlab.com/stopcoronavirus/website"
