image: monachus/hugo:v0.67.0

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  stage: deploy
  script:
  - rm -rf public
  - mkdir public
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
