image: monachus/hugo:v0.67.0

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  stage: deploy
  script:
    - mkdir .public
    - hugo --source "./" --destination ".public/"
    - echo ".PUBLIC"
    - ls .public
    - mv .public public
    - echo "PUBLIC"
    - ls public
  artifacts:
    paths:
    - public
  only:
    - master
