image: monachus/hugo:v0.67.0

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  stage: deploy
  script:
  - hugo --source="./hugo" --destination="./public"
  artifacts:
    paths:
    - public
  only:
  - master
